//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMonitor
    {
        public string Name { get; set; }
        public string Model { get; set; }
        public double Screen_Size { get; set; }
        public string Portability { get; set; }
        public string Touch_Screen { get; set; }
        public Nullable<int> No_of_Waveforms { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Care_Stage { get; set; }
    }
}
