//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatbotDataModelLibTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMonitor
    {
        public string Name { get; set; }
        public string Model { get; set; }
        public string Screen_Size { get; set; }
        public string Portability { get; set; }
        public string Touch_Screen { get; set; }
        public string Use { get; set; }
        public string Location { get; set; }
        public string Weight { get; set; }
        public string Care_Stage { get; set; }
    }
}
