//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatbotDataModelLibTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSale
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string ExecutiveName { get; set; }
        public string City { get; set; }
        public string Model { get; set; }
    }
}
