//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatbotDataModelLib.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhilipsDBEntities : DbContext
    {
        public PhilipsDBEntities()
            : base("name=PhilipsDBEntities")
        {
        }
    
    
        public virtual DbSet<CustomerData> CustomerDatas { get; set; }
        public virtual DbSet<PatientMonitor> PatientMonitors { get; set; }
        public virtual DbSet<PatientSale> PatientSales { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<SalesRep> SalesReps { get; set; }
    }
}
